version: '3.8'

services:
  # Chroma 向量数据库
  chromadb:
    image: chromadb/chroma:latest
    container_name: mem0-chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - PERSIST_DIRECTORY=/chroma/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Qdrant 向量数据库（备选）
  qdrant:
    image: qdrant/qdrant:latest
    container_name: mem0-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FalkorDB 图数据库（专为 GraphRAG 设计，支持向量相似度）
  falkordb:
    image: falkordb/falkordb:latest
    container_name: mem0-falkordb
    ports:
      - "6379:6379"  # Redis 协议端口
      - "3001:3000"  # FalkorDB Browser Web UI
    volumes:
      - ./falkordb_data:/var/lib/falkordb/data
    environment:
      - REDIS_PORT=6379
      - REDIS_BIND=0.0.0.0
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "GRAPH.LIST"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Ollama 嵌入服务（本地 LLM）
  ollama:
    image: ollama/ollama:latest
    container_name: mem0-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    command: ollama serve
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis（缓存和会话存储）
  redis:
    image: redis:7-alpine
    container_name: mem0-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma_data:
  qdrant_data:
  falkordb_data:
  falkordb_logs:
  ollama_data:
  redis_data: